### ISSUE TITLE
Comments metaboxes sometimes appear in Edit Post

### ISSUE THREAD

**Issue by fgilio** [solarissmoke/disable-comments-mu#9] opened 2016-02-29 18:41 UTC
Hi!

I've a dev site in my local machine where I see both Comments metaboxes in posts already published, that I imported from the staging site.
Not when I create a new one, neither when I edit one of those new posts.

I was using the standard version of the plugin and later switch to the mu version.

Do you know what could cause this behavior? Otherwise, how can I help you debug it?

Regards!

**Comment by szepeviktor** [comment] 2016-02-29 19:16
> You should delete all existing comments from the WordPress database before activating this plugin.

*from the README*

`wp comment delete $(wp comment list --format=ids)`

**Comment by fgilio** [comment] 2016-03-01 03:59
I have no data in wp_comments nor in wp_commentmeta, both tables are empty.

Here is a screenshot of the metaboxes I get in, i think, all imported posts: https://www.dropbox.com/s/416s2529wlqqeiu/Screenshot%202016-03-01%2000.57.36.png?dl=0

**Comment by szepeviktor** [comment] 2016-03-01 18:46
Maybe your import procedure was before activating `disable-comments-mu` or ignored some hooks.

**Comment by fgilio** [comment] 2016-03-02 01:05
Yeah, thanks!

I used this query:
`UPDATE wp_posts SET comment_status = 'closed';`

**Comment by solarissmoke** [comment] 2016-03-02 04:10
Hmm... those meta boxes should be hidden even if comments are open (the plugin removes support for comments). I will have a look some time and see why they are appearing.

**Comment by fgilio** [comment] 2016-03-02 12:43
Thank you @solarissmoke

**Comment by solarissmoke** [comment] 2016-03-05 05:03
@fgilio I have tested on a clean installation and cannot reproduce this issue. The only time the meta boxes are available is if a post already has comments on it (which is expected behaviour). In all other cases the meta boxes do not appear - even in the Screen Options list.

I'm not sure why you are seeing different behaviour - maybe another plugin is filtering `comments_open`? I'm going to close this for now but if you find where your issue is then feel free to reopen!

**Closed by solarissmoke** 2016-03-05 05:03 UTC

**Comment by fgilio** [comment] 2016-03-07 18:07
Thank you @solarissmoke, I'll reopen if I find out what happened. It all seems ok now :D
